# Generated by Django 5.1.6 on 2025-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
