# Generated by Django 4.2.20 on 2025-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STK_PUSH', '0002_registerchama_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerchama',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name_of_chama',
            field=models.CharField(max_length=50),
        ),
    ]
