# Generated by Django 4.2.20 on 2025-03-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STK_PUSH', '0003_alter_registerchama_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='articles/')),
            ],
        ),
    ]
